apiVersion: apps/v1
kind: Deployment
metadata:
  name: hoodle
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: hoodle
  template:
    metadata:
      labels:
        app: hoodle
    spec:
      containers:
      - name: hoodle-websocket
        image: gcr.io/${PROJECT_ID}/hoodle-websocket-docker:${APP_VERSION}
        ports:
        - containerPort: 8888
        env:
          - name: HOSTADDRESS
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: WSPORT
            value: "8888"
      - name: hoodle-webserver
        image: gcr.io/${PROJECT_ID}/hoodle-webserver-docker:${APP_VERSION}
        ports:
        - containerPort: 8080
