apiVersion: v1
kind: Service
metadata:
  name: hoodle-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: ws
    port: 7070
    targetPort: 8888
  selector:
    app: hoodle
  type: LoadBalancer
